/**
 * @file create-template.ts
 * @description Creates a professional DOCX template for Performance Improvement Plans (PIPs)
 * with properly formatted placeholders for use with docxtemplater.
 *
 * @usage
 * Run from project root:
 * ```bash
 * npx tsx scripts/create-template.ts
 * ```
 *
 * @output
 * - File: templates/pip-template.docx
 * - Contains placeholders: {title}, {date}, {pip_body}, {language}
 *
 * @placeholders
 * - {title} - Document title (e.g., "Performance Improvement Plan")
 * - {date} - Current date in YYYY-MM-DD format
 * - {pip_body} - Main PIP content (REQUIRED for docxtemplater)
 * - {language} - Output language code (e.g., "en", "fr")
 *
 * @notes
 * - This script uses the 'docx' npm package to programmatically create a DOCX file
 * - The resulting template is compatible with docxtemplater for runtime replacement
 * - Placeholders must be plain text (not Word fields) for docxtemplater compatibility
 * - The template includes professional formatting with margins and spacing
 *
 * @see scripts/test-template.ts - Test the generated template
 * @see scripts/README.md - Full documentation
 */

import { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } from "docx";
import * as fs from "fs";
import * as path from "path";

async function createTemplate() {
  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440, // 1 inch = 1440 twips
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        children: [
          // Header with title placeholder
          new Paragraph({
            text: "{title}",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 240 },
          }),

          // Document metadata
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
            children: [
              new TextRun({
                text: "Date: {date}",
                size: 20,
              }),
            ],
          }),

          // Separator line
          new Paragraph({
            text: "─".repeat(80),
            spacing: { after: 200 },
          }),

          // Main content area with placeholder
          new Paragraph({
            text: "{pip_body}",
            spacing: { before: 200 },
          }),

          // Footer separator
          new Paragraph({
            text: "",
            spacing: { before: 400 },
          }),

          new Paragraph({
            text: "─".repeat(80),
          }),

          // Document footer
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 200 },
            children: [
              new TextRun({
                text: "Generated by PIP Agent | Language: {language}",
                size: 18,
                italics: true,
                color: "666666",
              }),
            ],
          }),
        ],
      },
    ],
  });

  // Generate buffer
  const buffer = await Packer.toBuffer(doc);

  // Save to templates directory
  const templatePath = path.resolve(process.cwd(), "templates/pip-template.docx");
  fs.writeFileSync(templatePath, buffer);

  console.log("✅ Template created successfully!");
  console.log(`📄 Location: ${templatePath}`);
  console.log("\nTemplate includes these placeholders:");
  console.log("  • {title} - Document title");
  console.log("  • {date} - Current date");
  console.log("  • {pip_body} - Main PIP content (REQUIRED)");
  console.log("  • {language} - Output language");
}

createTemplate().catch((error: unknown) => {
  console.error("❌ Failed to create template:", error);
  process.exit(1);
});
